### ISSUE TITLE
archive-cleaner should output saved space

### ISSUE THREAD

**Issue by Bluewind** [archlinux/archivetools#2]
Right now, if the archive cleaner is used without --delete, it lists which packages it would remove, but it does not output the total space savings if all those files are removed. Seeing the potential space saving before actually deleting things would be nice to determine how many years we want to delete to free up space.

**Comment by jelly** [comment]
Has been implemented in https://github.com/archlinux/archivetools/commit/0fe6142d5bdee9b4b26e156703248b4704ab2f1e
